# Definindo o nome do meu Workflow
name: Meu Primeiro Workflow

# Definindo quando meu workflow é disparado.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
# Definindo os jobs que o workflow executará
jobs:
  jobs01:
    name: Executando job de teste
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Executando um comando simples.
        run: echo Olá Galera do Devops!

      # Runs a set of commands using the runners shell
      
