# This is a basic workflow to help you get started with Actions

name: Meu Primeiro Workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  jobs01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Olá Galera do Devops!

      # Runs a set of commands using the runners shell
      
