# Definindo o nome do meu Workflow
name: Meu Primeiro Workflow

# Definindo quando meu workflow é disparado.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
# Definindo os jobs que o workflow executará
jobs:
  jobs01:
    name: Executando job de teste
    runs-on: ubuntu-latest
    steps:
      - name: steps 1
      - uses: actions/checkout@v4
      
      - name: steps 2
        run: echo Olá Galera do Devops!
        
      - name: steps 3
        run: echo Olá Galera do Devops da steps 3!

      # Runs a set of commands using the runners shell
      
