# Definindo o nome do meu Workflow
name: Meu Primeiro Workflow

# Definindo quando meu workflow é disparado.
on:
  push:
    branches: [ "main" ]
    
# Definindo os jobs que o workflow executará
jobs:
  jobs01:
    name: Executando job de teste
    runs-on: ubuntu-latest
    steps:
     - name: steps 1
     - uses: actions/checkout@v4
